### ISSUE TITLE
VG  Create  Error

### ISSUE THREAD

**Issue by liyongxian** [alibaba/open-local#121]
### Ⅰ. Issue Description
NodeLocalStorage's Status Is Null.
![image](https://user-images.githubusercontent.com/18571576/162185231-aef6edbc-6513-4a25-9a86-649b049b479d.png)

### Ⅱ. Describe what happened
Install Open-local By Chart,Worker Of Kubernetes Adding Raw Device,But VG In The Worker Is Not.Then Check NLS status,Find It Was Null. 

### Ⅲ. Describe what you expected to happen
VG In The Worker Of Raw Device Is Fine. 
### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. helm install open-local
2.vgs in Worker
3. kubectl get nls

### Ⅴ. Anything else we need to know?
1、Scheduler Process
![image](https://user-images.githubusercontent.com/18571576/162187548-3af16853-a2da-4850-9c71-489f73fb0fe5.png)
2、scheduler-policy-config.json
![image](https://user-images.githubusercontent.com/18571576/162187635-1fffaef4-76fe-43ce-81c9-c20730d713b3.png)
3、driver-registrar Logs
![image](https://user-images.githubusercontent.com/18571576/162186171-631bcb29-66c4-4b26-8eb7-e03c509c57d5.png)
4、Agent Logs
![image](https://user-images.githubusercontent.com/18571576/162186223-ce9cf1e0-3ae4-4869-982b-08c56c420ed8.png)
5、scheduler-extender Logs
![image](https://user-images.githubusercontent.com/18571576/162186433-d3552369-47f5-4c42-a11a-ed6e1b68a4a9.png)
6、NodeLocalStorageInitConfig
![image](https://user-images.githubusercontent.com/18571576/162189615-92068f7b-95f1-41c8-b131-416dbd4fbfa5.png)
7、Raw Device Of Worker
![image](https://user-images.githubusercontent.com/18571576/162189735-4ed1433f-8177-4e4b-accc-056e562db321.png)

### Ⅵ. Environment:
-Kubernetes Version
![image](https://user-images.githubusercontent.com/18571576/162187025-3e3a301b-325c-4f4d-9ac0-a5d990ad284c.png)

- Open-Local version:
![image](https://user-images.githubusercontent.com/18571576/162186528-7b46958e-26dc-4753-8e61-03dbaaba0f1c.png)

- OS (e.g. from /etc/os-release):
- 
![image](https://user-images.githubusercontent.com/18571576/162186577-e3ad71ba-0d69-4ff3-b0fa-cb8a04efd239.png)

- Kernel (e.g. `uname -a`):
- 
![image](https://user-images.githubusercontent.com/18571576/162186610-43abcc5c-ed27-48bf-8cb4-c59fa45c71e2.png)

- Install tools:
- 
![image](https://user-images.githubusercontent.com/18571576/162186645-95b8b129-c6af-4d06-ab15-a09c812c97c4.png)

Thanks

**Comment by TheBeatles1994** [comment]
check if the open-local controller is running and whether the component log is normal.

kubectl get po -nkube-system -l component=open-local-controller

**Comment by TheBeatles1994** [comment]
this is a k8s bug, see [here](https://github.com/kubernetes/kubernetes/issues/86811#issuecomment-808932761)

open-local can fix this by making the field metav1.Time a pointer.

**Comment by TheBeatles1994** [comment]
fixed by #122
