### ISSUE TITLE
mountpoint vs device?

### ISSUE THREAD

**Issue by liyimeng** [alibaba/open-local#163]
## Question

What is the difference between mountpoint and device? I could not find any doc about it. 

Is a mountpoint actaully device that is already format and mounted in a particular directory? if this is the case, what is the point to have it, why user just go with device?

**Comment by TheBeatles1994** [comment]
Your understanding of mountpoint is correct.  This is an ancient history, Alibaba used to use mountpoint type internally.  When open-local is open source, we plan to replace mountpoint with device.

**Comment by liyimeng** [comment]
@TheBeatles1994 Thanks a lot for the clarification.
