### ISSUE TITLE
snapshot-controller CrashLoopBackOff and pvc keep in pending status 

### ISSUE THREAD

**Issue by FreshMan123** [alibaba/open-local#172]
### Ⅰ. Issue Description
I follow the instruction install the open-local but it seems does not work correctly. Probably some bugs here. The snapshot-controller CrashLoopBackOff with the message "Failed to list v1 volumesnapshots with error=the server could not find the requested resource (get volumesnapshots.snapshot.storage.k8s.io)" . Besides,I create the example yaml and the pv keep in pending condition. I'm not sure whether it is the first one cause the second.

### Ⅱ. Describe what happened

**The snapshot-controller CrashLoopBackOff but crd exist(not sure for the version)**
![image](https://user-images.githubusercontent.com/13621884/189324509-58363f56-a616-413c-9c70-cdbc940f28cc.png)
![image](https://user-images.githubusercontent.com/13621884/189325604-b0d05d38-fee3-454c-aaa1-2f31b7b4d597.png)

**The open-local-controller also give the message Failed to watch v1.VolumeSnapshotClass**
![image](https://user-images.githubusercontent.com/13621884/189325937-a5e901be-7954-40ae-a906-b0a6a4fd5ec2.png)

**Check the clusterrole of open-local**
![image](https://user-images.githubusercontent.com/13621884/189326846-a3159c03-7528-4be5-97f4-633b8e2ba61d.png)

**The pvc in pending status**
![image](https://user-images.githubusercontent.com/13621884/189325064-30e5e8f1-9405-47cd-9a1d-fc6576b7ad69.png)
![image](https://user-images.githubusercontent.com/13621884/189324873-25e2b541-e91a-45e4-bd38-f0f84f1d56b0.png)
![image](https://user-images.githubusercontent.com/13621884/189328329-508b3ebc-8ab2-4140-8424-b9eae0b1b3e5.png)
![image](https://user-images.githubusercontent.com/13621884/189328528-2e33ea88-1738-48c5-8515-2678ce6a38a0.png)

**Extension scheduler give error message**
![image](https://user-images.githubusercontent.com/13621884/189328697-1bd8463d-2ba2-4a04-80b3-f16dacfd247f.png)
![image](https://user-images.githubusercontent.com/13621884/189328798-51d3ad9d-02ae-49e3-b6e6-20d627eefeba.png)

**The pod also pending** 
![image](https://user-images.githubusercontent.com/13621884/189327318-c785074d-f8e5-4252-af42-759c45a6cf09.png)

**Nodelocalstorage does not create successfully**
![image](https://user-images.githubusercontent.com/13621884/189325275-7609bfde-06ad-4dc7-9f42-3c813fa8b1fe.png)

**Double check the NodeLocalStorageInitConfig which is correct**
![image](https://user-images.githubusercontent.com/13621884/189327708-43e9a2b8-75d4-419d-8dcd-b7ff65e8e265.png)
![image](https://user-images.githubusercontent.com/13621884/189327989-afe5b299-dcd9-4f45-9d66-939652952a9c.png)

### Ⅲ. Describe what you expected to happen
the example yaml given by instruction create successfully

### Ⅵ. Environment:

- Open-Local version: v0.5.5
- OS (e.g. from /etc/os-release): centos 7.9
- Kernel (e.g. `uname -a`): Linux kube-control-2 3.10.0-1160.el7.x86_64 #1 SMP Wed Nov 18 03:43:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: helm
- Others:

**Comment by TheBeatles1994** [comment]
try installing volumesnapshot CR again: kubectl apply -f helm/crds/

**Comment by FreshMan123** [comment]
I found there are two version of crds in helm/crd. I am confused about which one should I use v1beta1 and another one
![image](https://user-images.githubusercontent.com/13621884/189854525-9e195247-399f-448a-b909-2112b66d0446.png)

**Comment by FreshMan123** [comment]
I figure out where is the problem. It seems the crd which use in controller is v1 and the v1beta1 is not using in the controller. however, in some case the crd create the v1beta1 firstly, the helm find the crd already exist ignore the  v1 version. Maybe remove the v1beta1 version if the controller not use this version?

**Comment by TheBeatles1994** [comment]
fixed by #175
