### ISSUE TITLE
question about snapshots in open-local

### ISSUE THREAD

**Issue by FreshMan123** [alibaba/open-local#176]
## Question

I am wondering how to use snapshot in open-local? Is there any instruction I can follow up ?

**Comment by FreshMan123** [comment]
It seems these two restrictions make the snapshot not very useful. 

Is any plan to do this part in the future?

**Comment by TheBeatles1994** [comment]
We use read-only snapshot to backup data. We planned to support readwrite snapshot before, but have no time for it. We need more contributor to make open-local more powerful.
