### ISSUE TITLE
multiple device support in open-local

### ISSUE THREAD

**Issue by FreshMan123** [alibaba/open-local#178]
## Question

Does open-local allow us to add more devices in NodeLocalStorageInitConfig. For example, we deploy the  open-local with /dev/vdb device then we change the NodeLocalStorageInitConfig like this 

  spec:
    globalConfig:
      listConfig:
        vgs:
          include:
          - open-local-pool-[0-9]+
      resourceToBeInited:
        vgs:
        **- devices:
          - /dev/vdb
          - /dev/vdc**
          name: open-local-pool-0

**Comment by TheBeatles1994** [comment]
If you have already deployed the open-local with one device, open-local do not support to expand a new PV(here is /dev/vdc) to existing VG. You can uninstall open-local, remove VG in node(use command `vgremove open-local-pool-0`), edit nlsc and reinstall.
