### ISSUE TITLE
question about monitor

### ISSUE THREAD

**Issue by FreshMan123** [alibaba/open-local#181]
## Question

I am wondering which service will provide the metrics? I found that the ServiceMonitor open-local give following message like this ：
spec:
  endpoints:
  - path: /metrics
    port: http-metrics
  jobLabel: app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      app: open-local

but there is no svc like  open-local only open-local-scheduler-extender svc exist. so I am so confused about which pod provides the metrics. Is that the open-local-controller ,agent or open-local-scheduler-extender(btw I have already set monitor to true)

**Comment by TheBeatles1994** [comment]
Metrics is provided by open-local-scheduler-extender

**Comment by FreshMan123** [comment]
thx
