### ISSUE TITLE
Helm install CSIDriver error

### ISSUE THREAD

**Issue by synkarius** [alibaba/open-local#2]
# System info
Via `uname -a && kubectl version && helm version && apt-show-versions lvm2 | grep amd`:
```
Linux master-node 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T17:57:25Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
version.BuildInfo{Version:"v3.6.3", GitCommit:"d506314abfb5d21419df8c7e7e68012379db2354", GitTreeState:"clean", GoVersion:"go1.16.5"}
lvm2:amd64/bionic-updates 2.02.176-4.1ubuntu3.18.04.3 uptodate
```

# Bug Description

## Setup
```
wget https://github.com/alibaba/open-local/archive/refs/tags/v0.1.1.zip
unzip v0.1.1.zip
cd open-local-0.1.1
```

## The Problem
Using release 0.1.1 of open-local and following the current user guide's instructions, when I run
```
helm install open-local ./helm
```
-- I get the following error:
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
```

**Comment by peter-wangxu** [comment]
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122

> The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22.

@synkarius we already tested on 1.16, 1.18, 1.20, not yet on 1.22.

@TheBeatles1994 we might need declare the supported k8s version

**Comment by TheBeatles1994** [comment]
> https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122
> 
> > The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22.
> 
> @synkarius we already tested on 1.16, 1.18, 1.20, not yet on 1.22.
> 
> @TheBeatles1994 we might need declare the supported k8s version

@peter-wangxu  we can declare that open-local only support k8s 1.18+.

**Comment by TheBeatles1994** [comment]
Fixed by #3

**Comment by cheyuexian** [comment]
> > https://kubernetes.io/docs/reference/using-api/deprecation-guide/#storage-resources-v122
> > > The storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass, and VolumeAttachment is no longer served as of v1.22.
> > 
> > 
> > @synkarius we already tested on 1.16, 1.18, 1.20, not yet on 1.22.
> > @TheBeatles1994 we might need declare the supported k8s version
> 
> @peter-wangxu we can declare that open-local only support k8s 1.18+.

my cluster version is 1.16,any history  version can i use?

**Comment by TheBeatles1994** [comment]
You can use storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass by modifying chart @cheyuexian

**Comment by cheyuexian** [comment]
> You can use storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass by modifying chart @cheyuexian

but in the code,listwatch or informer watch object`s version is  v1 . i got some error
![image](https://user-images.githubusercontent.com/14341344/133050240-5f2d313e-fba6-43a5-bb16-2047ee37f59b.png)

**Comment by TheBeatles1994** [comment]
![image](https://user-images.githubusercontent.com/27069322/133055174-f6ba6bc5-850e-4364-bad4-9b35ac872586.png)

url: https://kubernetes-csi.github.io/docs/external-provisioner.html

so you need modify csi sidecar image:
- k8s.gcr.io/sig-storage/csi-provisioner: v2.2.2 -> v1.6.1

and snapshot is not supported by yoda in k8s 1.16. @cheyuexian

**Comment by TheBeatles1994** [comment]
> > You can use storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass by modifying chart @cheyuexian
> 
> but in the code,listwatch or informer watch object`s version is v1 . i got some errors
> ![image](https://user-images.githubusercontent.com/14341344/133050240-5f2d313e-fba6-43a5-bb16-2047ee37f59b.png)

Which component does the log come from?

**Comment by cheyuexian** [comment]
> > > You can use storage.k8s.io/v1beta1 API version of CSIDriver, CSINode, StorageClass by modifying chart @cheyuexian
> > 
> > 
> > but in the code,listwatch or informer watch object`s version is v1 . i got some errors
> > ![image](https://user-images.githubusercontent.com/14341344/133050240-5f2d313e-fba6-43a5-bb16-2047ee37f59b.png)
> 
> Which component does the log come from?

from open-local-csi-provisioner .  ok i try use k8s.gcr.io/sig-storage/csi-provisioner: v2.2.2 -> v1.6.1,thanks
