### ISSUE TITLE
image pull failed

### ISSUE THREAD

**Issue by wujy189** [alibaba/open-local#213]
Problem:  
Warning  Failed     16m (x2 over 16m)   kubelet            Failed to pull image "ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/open-local:v0.7.1": rpc error: code = NotFound desc = failed to pull and unpack image "ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/open-local:v0.7.1": failed to resolve reference "ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/open-local:v0.7.1": ack-agility-registry.cn-shanghai.cr.aliyuncs.com/ecp_builder/open-local:v0.7.1: not found

**Comment by caijian76** [comment]
me too

**Comment by peter-wangxu** [comment]
The image service should be recovered now, sorry for the inconvience

**Comment by fourierrr** [comment]
hello， @peter-wangxu 

Unable to access ack-agility-registry.cn-shanghai.cr.aliyuncs.com.

is the  image service down again?

**Comment by peter-wangxu** [comment]
Please use latest version which use docker hub image

**Comment by fourierrr** [comment]
@peter-wangxu  thank you!! the main branch is okay 🎉🎉

Have you considered adding a tag for the latest version? I noticed that the latest release is still 0.7.1, so I encountered the image issue while using 0.7.1
