### ISSUE TITLE
IO 限流没有生效

### ISSUE THREAD

**Issue by shaolila** [alibaba/open-local#219]
## Question

io 限流这块,我测试的没有生效,请教一下怎么才能做到对 IO 的限流呢?
![image](https://github.com/alibaba/open-local/assets/8872412/53d03321-2a3b-4c15-a3fc-b01cd354b729)

使用的 storageclass 是open-local-lvm-io-throttling :
![image](https://github.com/alibaba/open-local/assets/8872412/9a6d3b60-7192-4fe9-85d6-d13b943de2c1)
使用的sts 的 pod 的 yaml
[sts-io-throttling-fio.yaml.zip](https://github.com/alibaba/open-local/files/12025374/sts-io-throttling-fio.yaml.zip)

pod报错
I0712 01:34:42.225552   16190 nodeutils.go:48] createLV: vg open-local-pool-0, volume local-c1146907-df09-45fd-a23c-e67d86e11ebe, LVM Type linear
E0712 01:34:42.225648   16190 driver.go:109] GRPC error: rpc error: code = Internal desc = NodePublishVolume(mountLvmBlock): fail to mount lvm volume local-c1146907-df09-45fd-a23c-e67d86e11ebe with path /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/local-c1146907-df09-45fd-a23c-e67d86e11ebe/8d7f748f-108d-4418-af17-84481fc27e65: rpc error: code = Internal desc = mountLvmBlock: check if /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/local-c1146907-df09-45fd-a23c-e67d86e11ebe/8d7f748f-108d-4418-af17-84481fc27e65 is mountpoint failed: stat /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/local-c1146907-df09-45fd-a23c-e67d86e11ebe/8d7f748f-108d-4418-af17-84481fc27e65: no such file or directory

**Comment by shaolila** [comment]
openlocal-agent 中 csi-Plugin 有报错信息
[csi-Plugin.log.txt](https://github.com/alibaba/open-local/files/12039445/csi-Plugin.log.txt)

**Comment by lihezhong93** [comment]
volumeDevices:
        - devicePath: "/dev/vdd"
          name: html
换成
          volumeMounts:
          - mountPath: /test
            name: html

**Comment by peter-wangxu** [comment]
fixed in latest version(v0.7.1)

**Comment by kwenzh** [comment]
mark
