### ISSUE TITLE
是否支持动态扩容磁盘

### ISSUE THREAD

**Issue by dxygit1** [alibaba/open-local#224]
## Question

我第一次添加了一块vdc的盘到vg1中
![image](https://github.com/alibaba/open-local/assets/57128304/93047851-dcb6-47be-bf21-51b2e2402bd6)

我第二次想把vdd这块盘添加到这个vg中，这个要怎么加一下呀。我尝试添加在NodeLocalStorageInitConfig中并没有创建对应的pv

**Comment by peter-wangxu** [comment]
可以尝试下把对应节点的nodelocalstorage删除，看看会不会扩容，具体代码逻辑晚点看下

**Comment by dxygit1** [comment]
我尝试过卸载open-local 删除nodelocalstorage  在重新install一样也是不可以的。   另外我这个用的是阿里云ack测试的，

**Comment by shaolila** [comment]
> ## Question
> 我第一次添加了一块vdc的盘到vg1中 ![image](https://user-images.githubusercontent.com/57128304/258962492-93047851-dcb6-47be-bf21-51b2e2402bd6.png)
> 
> 我第二次想把vdd这块盘添加到这个vg中，这个要怎么加一下呀。我尝试添加在NodeLocalStorageInitConfig中并没有创建对应的pv

在每个节点上执行 vgextend open-local-0 /dev/vdc ，集群会自动更新并认识扩容的 vg容量

**Comment by dxygit1** [comment]
好的  明白  这个要手动添加到vg是吧。谢谢您。我手动添加是可以的，我以为在yaml中加进去 磁盘会自己加进去
