### ISSUE TITLE
reference dependency error

### ISSUE THREAD

**Issue by 2366252403** [alibaba/open-local#266]
### Ⅰ. Issue Description
I'm trying to reference this, but when I run it I get an error, one of the versions he depends on seems to be missing, causing this error
![image](https://github.com/user-attachments/assets/ebcd4d4d-16ac-471f-8e6f-0c54436ca3e7)

### Ⅲ. Describe what you expected to happen
go.mod
github.com/peter-wangxu/simple-golang-tools v0.0.0-20210209091758-458c22961dd2

error info:x
go: github.com/alibaba/open-local@v0.7.0 requires
        github.com/peter-wangxu/simple-golang-tools@v0.0.0-20210209091758-458c22961dd2: invalid version: unknown revision 458c22961dd2
version info：
https://pkg.go.dev/github.com/peter-wangxu/simple-golang-tools

### Ⅵ. Environment:

- Open-Local version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by peter-wangxu** [comment]
Yes, open-local needs to update the ref as well
