### ISSUE TITLE
device schedule with error Get Response StatusCode 500

### ISSUE THREAD

**Issue by Seryta** [alibaba/open-local#66]
### Ⅰ. Issue Description
新建 pvc 时报错
```
  Normal   WaitForFirstConsumer  2m13s                 persistentvolume-controller                                      waiting for first consumer to be created before binding
  Normal   ExternalProvisioning  11s (x11 over 2m13s)  persistentvolume-controller                                      waiting for a volume to be created, either by external provisioner "local.csi.aliyun.com" or manually created by system administrator
  Normal   Provisioning          6s (x8 over 2m13s)    local.csi.aliyun.com_node1_080636cb-a68d-4ee8-a3a3-db5ae5634cbb  External provisioner is provisioning volume for claim "demo/pvc-open-local-device-hdd-test2-0-d0"
  Warning  ProvisioningFailed    6s (x8 over 2m13s)    local.csi.aliyun.com_node1_080636cb-a68d-4ee8-a3a3-db5ae5634cbb  failed to provision volume with StorageClass "open-local-device-hdd": rpc error: code = InvalidArgument desc = Parse Device part schedule info error rpc error: code = InvalidArgument desc = device schedule with error Get Response StatusCode 500, Response: failed to allocate local storage for pvc demo/pvc-open-local-device-hdd-test2-0-d0: Insufficient Device storage, requested 0, available 0, capacity 0
```

### Ⅱ. Describe what happened
我是在 k3s 集群中部署的 open-local，但是因为 k3s 没有 kube-scheduler 相关配置文件，所以 init-job 无法正常运行。
```
modifying kube-scheduler.yaml...
grep: /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
+ sed -i '/  hostNetwork: true/a \  dnsPolicy: ClusterFirstWithHostNet' /etc/kubernetes/manifests/kube-scheduler.yaml
sed: can't read /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
```
其他相关配置都运行良好：
```
NAME                                              READY   STATUS    RESTARTS   AGE
open-local-agent-7sd9d                            3/3     Running   0          22h
open-local-csi-provisioner-785b7f99bd-hlqdv       1/1     Running   0          22h
open-local-agent-8kg4r                            3/3     Running   0          22h
open-local-agent-jljlv                            3/3     Running   0          22h
open-local-scheduler-extender-5d48bc465c-r42pn    1/1     Running   0          22h
open-local-snapshot-controller-785987975c-hhgr7   1/1     Running   0          22h
open-local-csi-snapshotter-5f797c4596-wml76       1/1     Running   0          22h
open-local-csi-resizer-7c9698976f-f7tzz           1/1     Running   0          22h

master1 [~]$ kubectl get nodelocalstorage -ojson master1|jq .status.filteredStorageInfo
{
  "updateStatusInfo": {
    "lastUpdateTime": "2021-11-12T11:02:56Z",
    "updateStatus": "accepted"
  },
  "volumeGroups": [
    "open-local-pool-0"
  ]
}
master1 [~]$ kubectl get nodelocalstorage -ojson node1|jq .status.filteredStorageInfo
{
  "updateStatusInfo": {
    "lastUpdateTime": "2021-11-12T11:01:56Z",
    "updateStatus": "accepted"
  },
  "volumeGroups": [
    "open-local-pool-0"
  ]
}
master1 [~]$ kubectl get nodelocalstorage -ojson node2|jq .status.filteredStorageInfo
{
  "updateStatusInfo": {
    "lastUpdateTime": "2021-11-12T11:02:56Z",
    "updateStatus": "accepted"
  },
  "volumeGroups": [
    "open-local-pool-0"
  ]
}
```
所以我怀疑是调度的问题导致无法正常创建 PVC/PV

### Ⅲ. Describe what you expected to happen
希望能够在 k3s 正常部署运行 open-local

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1. 建议参考 [k8s-scheduler-extender](https://github.com/everpeace/k8s-scheduler-extender-example/blob/master/extender.yaml)的方式实现调度的自定义，兼容 k3s 等其他平台

### Ⅵ. Environment:

- Open-Local version:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by TheBeatles1994** [comment]
我看到你的报错是：
```
Insufficient Device storage, requested 0, available 0, capacity 0
```

而你本地只有VG：
```
{
  "updateStatusInfo": {
    "lastUpdateTime": "2021-11-12T11:02:56Z",
    "updateStatus": "accepted"
  },
  "volumeGroups": [
    "open-local-pool-0"
  ]
}
```

所以你应该指定storageclass为 open-local-lvm 才行

**Comment by TheBeatles1994** [comment]
你之前指定的sc应该是 open-local-device-hdd，这个是独占盘类型，见[文档说明](https://github.com/alibaba/open-local/blob/main/docs/user-guide/user-guide_zh_CN.md#%E5%AD%98%E5%82%A8%E7%B1%BB%E5%9E%8B%E4%BB%8B%E7%BB%8D)

**Comment by Seryta** [comment]
> 你之前指定的sc应该是 open-local-device-hdd，这个是独占盘类型，见[文档说明](https://github.com/alibaba/open-local/blob/main/docs/user-guide/user-guide_zh_CN.md#%E5%AD%98%E5%82%A8%E7%B1%BB%E5%9E%8B%E4%BB%8B%E7%BB%8D)

的确是这样，非常感谢，另外请问 init-job 的报错，会影响到哪些？

```
modifying kube-scheduler.yaml...
grep: /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
+ sed -i '/  hostNetwork: true/a \  dnsPolicy: ClusterFirstWithHostNet' /etc/kubernetes/manifests/kube-scheduler.yaml
sed: can't read /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
```

**Comment by TheBeatles1994** [comment]
> > 你之前指定的sc应该是 open-local-device-hdd，这个是独占盘类型，见[文档说明](https://github.com/alibaba/open-local/blob/main/docs/user-guide/user-guide_zh_CN.md#%E5%AD%98%E5%82%A8%E7%B1%BB%E5%9E%8B%E4%BB%8B%E7%BB%8D)
> 
> 的确是这样，非常感谢，另外请问 init-job 的报错，会影响到哪些？
> 
> ```
> modifying kube-scheduler.yaml...
> grep: /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
> + sed -i '/  hostNetwork: true/a \  dnsPolicy: ClusterFirstWithHostNet' /etc/kubernetes/manifests/kube-scheduler.yaml
> sed: can't read /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
> ```

你的k8s集群是怎么拉起的？ init-job是为了配置kube-scheduler，即为kube-scheduler加上一行参数，使其扩展存储调度算法。如果你的kube-scheduler不是static pod，那init-job会无效，也会报错。

**Comment by Seryta** [comment]
> > > 你之前指定的sc应该是 open-local-device-hdd，这个是独占盘类型，见[文档说明](https://github.com/alibaba/open-local/blob/main/docs/user-guide/user-guide_zh_CN.md#%E5%AD%98%E5%82%A8%E7%B1%BB%E5%9E%8B%E4%BB%8B%E7%BB%8D)
> > 
> > 
> > 的确是这样，非常感谢，另外请问 init-job 的报错，会影响到哪些？
> > ```
> > modifying kube-scheduler.yaml...
> > grep: /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
> > + sed -i '/  hostNetwork: true/a \  dnsPolicy: ClusterFirstWithHostNet' /etc/kubernetes/manifests/kube-scheduler.yaml
> > sed: can't read /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
> > ```
> 
> 你的k8s集群是怎么拉起的？ init-job是为了配置kube-scheduler，即为kube-scheduler加上一行参数，使其扩展存储调度算法。如果你的kube-scheduler不是static pod，那init-job会无效，也会报错。

我的是 k3s 集群，没办法添加这行参数

**Comment by TheBeatles1994** [comment]
> > > > 你之前指定的sc应该是 open-local-device-hdd，这个是独占盘类型，见[文档说明](https://github.com/alibaba/open-local/blob/main/docs/user-guide/user-guide_zh_CN.md#%E5%AD%98%E5%82%A8%E7%B1%BB%E5%9E%8B%E4%BB%8B%E7%BB%8D)
> > > 
> > > 
> > > 的确是这样，非常感谢，另外请问 init-job 的报错，会影响到哪些？
> > > ```
> > > modifying kube-scheduler.yaml...
> > > grep: /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
> > > + sed -i '/  hostNetwork: true/a \  dnsPolicy: ClusterFirstWithHostNet' /etc/kubernetes/manifests/kube-scheduler.yaml
> > > sed: can't read /etc/kubernetes/manifests/kube-scheduler.yaml: No such file or directory
> > > ```
> > 
> > 
> > 你的k8s集群是怎么拉起的？ init-job是为了配置kube-scheduler，即为kube-scheduler加上一行参数，使其扩展存储调度算法。如果你的kube-scheduler不是static pod，那init-job会无效，也会报错。
> 
> 我的是 k3s 集群，没办法通过 init-job 添加这行参数，所以能不能通过其他方式实现

如果不是static pod，只有手动配置kube-scheduler了。

**Comment by TheBeatles1994** [comment]
目前open-local在调度部分的实现就是基于 k8s-scheduler-extender的方式，所以也是兼容 k3s 等其他平台的。

如果没有问题的话，这个issue我先close了
