### ISSUE TITLE
kube-scheduler config setting?

### ISSUE THREAD

**Issue by cheyuexian** [alibaba/open-local#7]
没找到调度器扩展的配置

**Comment by TheBeatles1994** [comment]
@cheyuexian you can find /etc/kubernetes/scheduler-policy-config.json in every master.

https://github.com/alibaba/open-local/blob/main/helm/templates/init-job.yaml

**Comment by cheyuexian** [comment]
thanks very much

**Comment by cheyuexian** [comment]
well done

**Comment by cheyuexian** [comment]
> @cheyuexian you can find /etc/kubernetes/scheduler-policy-config.json in every master node.
> 
> https://github.com/alibaba/open-local/blob/main/helm/templates/init-job.yaml

by the way

**Comment by cheyuexian** [comment]
> @cheyuexian you can find /etc/kubernetes/scheduler-policy-config.json in every master node.
> 
> https://github.com/alibaba/open-local/blob/main/helm/templates/init-job.yaml

by the way,my cluster version 1.16. any history version can i use
