### ISSUE TITLE
Report more details or solution when throwing error

### ISSUE THREAD

**Issue by allencloud** [alibaba/open-local#78]
## Why you need it?

![image](https://user-images.githubusercontent.com/9465626/144233518-5da3d8d1-a5dd-434c-bde8-d4dec1eb5e70.png)

When user rans into such an error, he does not know how to solve it at all.

I wish the error reporting should carry more details or brief solution in the message.

The concrete code is above:
https://github.com/alibaba/open-local/blob/952eadbb4a8e74ace367cc89daaa53546b80256c/pkg/scheduler/errors/predicate.go#L65-L67

**Comment by TheBeatles1994** [comment]
fixed by #79 #80
